WIP: Write and edit an article
cafebabel/cafebabel.com pull request #41
Opened 2017-11-02 04:19 UTC by vinyll

Missing languages selection, categories selection, status select, markdown rendering, image upload … and tests!

2017-11-02 12:53 UTC, davidbgk commented on templates/profile.html
> +<<<<<<< HEAD
💣

2017-11-02 12:54 UTC, davidbgk commented on cafebabel/articles/views.py
> +    if article.status == 'draft':
Maybe add a `is_draft` property?

2017-11-03 02:39 UTC, davidbgk commented on cafebabel/articles/models.py
> +            return f'{app.config.get("ARTICLES_IMAGES_URL")}/{self.image}'
You should be able to do directly `return app.config.get("ARTICLES_IMAGES_URL") / self.image`

2017-11-03 02:40 UTC, davidbgk commented on cafebabel/articles/models.py
> +        if document.status == 'published' and not document.publication_date:
Can't you reuse `is_published`?

2017-11-03 02:45 UTC, davidbgk commented on templates/profile.html
> +  <form class=user-save data-method=put action={{ url_for('api_user_put', id=user.id) }}>
Does it work?

2017-11-03 02:47 UTC, vinyll commented on templates/profile.html
> +  <form class=user-save data-method=put action={{ url_for('api_user_put', id=user.id) }}>
Seems like it

2017-11-03 13:03 UTC, davidbgk requested changes

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/models.py
> +    status = db.StringField(default='draft')
How many statuses do we have? Maybe a `is_draft` boolean field (or even better datetime field) would suffice?

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/models.py
> +    def update_slug(cls, sender, document, **kwargs):
Beware here, it means the slug must not be significative within the URL, ever. Or we need to deal with history and redirections…

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/models.py
> +        if document.image:
Why not call `document.delete_image()`?

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/models.py
> +            document._upload_image = None
I don't get why we reset to `None`?

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/views.py
> +@app.route('/article/write/')
`write` looks unusual to me, `new`?

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/views.py
> +    return render_template('articles/edit.html', article=article,
Consistency route/template names.

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/articles/views.py
> +        Article.objects.get(id=id).delete()
No soft delete? 💣

2017-11-03 13:03 UTC, davidbgk commented on cafebabel/users/models.py
> +    roles = db.ListField(db.ReferenceField(Role, reverse_delete_rule=db.PULL),
What does it mean? Role deletion on user deletion?

2017-11-03 13:03 UTC, davidbgk commented on settings.py
> +ARTICLES_IMAGES_PATH = Path(__file__).parent / 'static/uploads/articles'
I think the philosophy behind Path is to use `Path() / 'static' / 'blah'` and let Python deal with separators.

2017-11-03 14:19 UTC, davidbgk commented on cafebabel/articles/models.py
> +from hashlib import md5
Useless import

2017-11-03 14:19 UTC, davidbgk commented on cafebabel/articles/models.py
> +    def delete_image(cls, sender, document, **kwargs):
Redefining a function with the same name is confusing, not sure if the first is actually in use?

2017-11-06 22:25 UTC, vinyll commented on cafebabel/__init__.py
> +from .core.routing import ArticleConverter  # noqa: F401
Better remove the `F401` qa code if it's not the right one ;)

2017-11-06 22:25 UTC, vinyll commented on cafebabel/articles/views.py
> +@app.route('/article/<article(status="published"):article>/')
Mindblow!! 😮

2017-11-06 22:25 UTC, vinyll commented on cafebabel/articles/views.py
> +        article = Article.objects.get(id=draft_id)
Ensure the status is _draft_.
Eventually redirect to the published article otherwise?

2017-11-06 22:25 UTC, vinyll commented on cafebabel/articles/views.py
> +    flash('Your article was successfully saved.')
This looks like a plain copy/paste from draft_edit. Refactor?

2017-11-06 22:25 UTC, vinyll commented on cafebabel/articles/views.py
> +    except (Article.DoesNotExist, mongoengine.errors.ValidationError):
Can you still get a ValidationError with the regex in the URL?

2017-11-06 22:25 UTC, vinyll commented on cafebabel/tests/test_articles.py
> +    assert 'action=/proposal/' in response.get_data().decode()
`response.get_data(as_text=True)`

2017-11-07 01:04 UTC, vinyll commented
@davidbgk: LGTM. Let me know what you say so we can merge/deploy.

2017-11-07 01:48 UTC, davidbgk commented
@vinyll great refactoring, let's get this merged/deployed!

2017-11-07 01:48 UTC, davidbgk approved these changes

2017-11-07 09:02 UTC, merged