add meta viewport
cafebabel/cafebabel.com pull request #52
Opened 2017-11-10 17:21 UTC by cafebabel-webmaster

2017-11-10 18:19 UTC, vinyll approved these changes

2017-11-10 18:39 UTC, davidbgk requested changes

2017-11-10 18:39 UTC, davidbgk commented on templates/base.html
> +<meta name=viewport content="width=device-width, user-scalable=no">
Latest recommendations are more complete: https://codepen.io/tigt/post/meta-viewport-for-2015

2017-11-13 19:47 UTC, davidbgk approved these changes

2017-11-14 11:53 UTC, merged